name: Rust CI

on:
  push:
    branches:
      - "**" # Run for all branches on commit
  pull_request:
    branches:
      - "**" # Run for all pull requests

jobs:
  msrv:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Test on both Linux and Windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.78.0 # Minimum Supported Rust Version (MSRV)
          override: true

      # - name: Install Criterion for Benchmarks
      #   run: |
      #     rustup component add clippy

      - name: Build and Test
        run: |
          cargo build --release
          cargo test

      - name: Run Benchmarks
        run: cargo bench --features bench

  latest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Latest Stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # - name: Install Criterion for Benchmarks
      #   run: |
      #     rustup component add clippy
      #     cargo install cargo-benchcmp # Example, if additional bench tools are needed

      - name: Build and Test
        run: |
          cargo build --release
          cargo test

      - name: Run Benchmarks
        run: cargo bench --features bench
